### ISSUE TITLE
Module - 基本防刷屏

### ISSUE THREAD

**Issue by quininer** [quininer/botlord#1]
防止 恶意 及 错误粘贴 导致的刷屏。
## v1
- 以 mask 为标准保留用户的 10条 频道内PRIVMSG记录。
- 收到第11条 频道内PRIVMG记录 时，检查并弹出第一条记录，如果首尾相差时间在 30s 内，则禁言 30s。

---
## v2
- 以 mask 为标准保留用户的 10条 频道内PRIVMSG记录 时间 及 与上一条消息相差的 时间间隔。
- 收到第11条 频道内PRIVMG记录 时，检查并弹出第`违规次数+1`条记录，如果 平均间隔 少于`(违规次数+1)*3`s，则禁言 `违规次数*30`s 并以 mask 为标准增加违规次数。
- ~~若 最新消息 的内容和 记录里有 至少三条重复时， 增加违规次数(不触发禁言)。~~
- 禁言结束之后三分钟，违规次数 - 1。

**Comment by pocmon** [comment]
已阅，通过

**Comment by riaqn** [comment]
可以, 以后可以逐步完善.

**Comment by zsrkmyn** [comment]
I vote yes.

**Comment by renormalizable** [comment]
+1

**Comment by quininer** [comment]
此提案通过并完成 :)
虽然不完美且与描述有区别。
